//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *ChangeGuard) DeepCopyInto(out *ChangeGuard) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopyObject returns a generically typed copy of an object that is in memory.
// The input object is not touched.
func (in *ChangeGuard) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopy returns a deep copy of a ChangeGuard.
func (in *ChangeGuard) DeepCopy() *ChangeGuard {
	if in == nil {
		return nil
	}
	out := new(ChangeGuard)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *ChangeGuardList) DeepCopyInto(out *ChangeGuardList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ChangeGuard, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopyObject returns a generically typed copy of an object that is in memory.
// The input object is not touched.
func (in *ChangeGuardList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopy returns a deep copy of a ChangeGuardList.
func (in *ChangeGuardList) DeepCopy() *ChangeGuardList {
	if in == nil {
		return nil
	}
	out := new(ChangeGuardList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *ChangeGuardSpec) DeepCopyInto(out *ChangeGuardSpec) {
	*out = *in
	in.Subject.DeepCopyInto(&out.Subject)
	if in.Operations != nil {
		in, out := &in.Operations, &out.Operations
		*out = make([]OperationType, len(*in))
		copy(*out, *in)
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]GuardRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of a ChangeGuardSpec.
func (in *ChangeGuardSpec) DeepCopy() *ChangeGuardSpec {
	if in == nil {
		return nil
	}
	out := new(ChangeGuardSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *ChangeGuardStatus) DeepCopyInto(out *ChangeGuardStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of a ChangeGuardStatus.
func (in *ChangeGuardStatus) DeepCopy() *ChangeGuardStatus {
	if in == nil {
		return nil
	}
	out := new(ChangeGuardStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *SubjectResource) DeepCopyInto(out *SubjectResource) {
	*out = *in
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy returns a deep copy of a SubjectResource.
func (in *SubjectResource) DeepCopy() *SubjectResource {
	if in == nil {
		return nil
	}
	out := new(SubjectResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *GuardRule) DeepCopyInto(out *GuardRule) {
	*out = *in
	if in.ExistingResources != nil {
		in, out := &in.ExistingResources, &out.ExistingResources
		*out = new(ExistingResourcesCheck)
		(*in).DeepCopyInto(*out)
	}
	if in.ExpressionCheck != nil {
		in, out := &in.ExpressionCheck, &out.ExpressionCheck
		*out = new(ExpressionCheck)
		**out = **in
	}
}

// DeepCopy returns a deep copy of a GuardRule.
func (in *GuardRule) DeepCopy() *GuardRule {
	if in == nil {
		return nil
	}
	out := new(GuardRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *ExistingResourcesCheck) DeepCopyInto(out *ExistingResourcesCheck) {
	*out = *in
	if in.LabelSelector != nil {
		in, out := &in.LabelSelector, &out.LabelSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.SameNamespace != nil {
		in, out := &in.SameNamespace, &out.SameNamespace
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy returns a deep copy of a ExistingResourcesCheck.
func (in *ExistingResourcesCheck) DeepCopy() *ExistingResourcesCheck {
	if in == nil {
		return nil
	}
	out := new(ExistingResourcesCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy returns a deep copy of an ExpressionCheck.
func (in *ExpressionCheck) DeepCopy() *ExpressionCheck {
	if in == nil {
		return nil
	}
	out := new(ExpressionCheck)
	*out = *in
	return out
}
