//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *ChangeValidator) DeepCopyInto(out *ChangeValidator) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopyObject returns a generically typed copy of an object that is in memory.
// The input object is not touched.
func (in *ChangeValidator) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopy returns a deep copy of a ChangeValidator.
func (in *ChangeValidator) DeepCopy() *ChangeValidator {
	if in == nil {
		return nil
	}
	out := new(ChangeValidator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *ChangeValidatorList) DeepCopyInto(out *ChangeValidatorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ChangeValidator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopyObject returns a generically typed copy of an object that is in memory.
// The input object is not touched.
func (in *ChangeValidatorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopy returns a deep copy of a ChangeValidatorList.
func (in *ChangeValidatorList) DeepCopy() *ChangeValidatorList {
	if in == nil {
		return nil
	}
	out := new(ChangeValidatorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *ChangeValidatorSpec) DeepCopyInto(out *ChangeValidatorSpec) {
	*out = *in
	in.Subject.DeepCopyInto(&out.Subject)
	if in.Operations != nil {
		in, out := &in.Operations, &out.Operations
		*out = make([]OperationType, len(*in))
		copy(*out, *in)
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]GuardRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of a ChangeValidatorSpec.
func (in *ChangeValidatorSpec) DeepCopy() *ChangeValidatorSpec {
	if in == nil {
		return nil
	}
	out := new(ChangeValidatorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *ChangeValidatorStatus) DeepCopyInto(out *ChangeValidatorStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of a ChangeValidatorStatus.
func (in *ChangeValidatorStatus) DeepCopy() *ChangeValidatorStatus {
	if in == nil {
		return nil
	}
	out := new(ChangeValidatorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *SubjectResource) DeepCopyInto(out *SubjectResource) {
	*out = *in
	if in.Names != nil {
		in, out := &in.Names, &out.Names
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy returns a deep copy of a SubjectResource.
func (in *SubjectResource) DeepCopy() *SubjectResource {
	if in == nil {
		return nil
	}
	out := new(SubjectResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *GuardRule) DeepCopyInto(out *GuardRule) {
	*out = *in
	if in.ExistingResources != nil {
		in, out := &in.ExistingResources, &out.ExistingResources
		*out = new(ExistingResourcesCheck)
		(*in).DeepCopyInto(*out)
	}
	if in.ExpressionCheck != nil {
		in, out := &in.ExpressionCheck, &out.ExpressionCheck
		*out = new(ExpressionCheck)
		**out = **in
	}
	if in.NameReferenceCheck != nil {
		in, out := &in.NameReferenceCheck, &out.NameReferenceCheck
		*out = new(NameReferenceCheck)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy returns a deep copy of a GuardRule.
func (in *GuardRule) DeepCopy() *GuardRule {
	if in == nil {
		return nil
	}
	out := new(GuardRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *ExistingResourcesCheck) DeepCopyInto(out *ExistingResourcesCheck) {
	*out = *in
	if in.LabelSelector != nil {
		in, out := &in.LabelSelector, &out.LabelSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.SameNamespace != nil {
		in, out := &in.SameNamespace, &out.SameNamespace
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy returns a deep copy of a ExistingResourcesCheck.
func (in *ExistingResourcesCheck) DeepCopy() *ExistingResourcesCheck {
	if in == nil {
		return nil
	}
	out := new(ExistingResourcesCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy returns a deep copy of an ExpressionCheck.
func (in *ExpressionCheck) DeepCopy() *ExpressionCheck {
	if in == nil {
		return nil
	}
	out := new(ExpressionCheck)
	*out = *in
	return out
}

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *NameReferenceCheck) DeepCopyInto(out *NameReferenceCheck) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]NameReferenceResource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SameNamespace != nil {
		in, out := &in.SameNamespace, &out.SameNamespace
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy returns a deep copy of a NameReferenceCheck.
func (in *NameReferenceCheck) DeepCopy() *NameReferenceCheck {
	if in == nil {
		return nil
	}
	out := new(NameReferenceCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *NameReferenceResource) DeepCopyInto(out *NameReferenceResource) {
	*out = *in
	if in.NameFields != nil {
		in, out := &in.NameFields, &out.NameFields
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy returns a deep copy of a NameReferenceResource.
func (in *NameReferenceResource) DeepCopy() *NameReferenceResource {
	if in == nil {
		return nil
	}
	out := new(NameReferenceResource)
	in.DeepCopyInto(out)
	return out
}
