//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *ClusterChangeValidator) DeepCopyInto(out *ClusterChangeValidator) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopyObject returns a generically typed copy of an object that is in memory.
// The input object is not touched.
func (in *ClusterChangeValidator) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopy returns a deep copy of a ClusterChangeValidator.
func (in *ClusterChangeValidator) DeepCopy() *ClusterChangeValidator {
	if in == nil {
		return nil
	}
	out := new(ClusterChangeValidator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *ClusterChangeValidatorList) DeepCopyInto(out *ClusterChangeValidatorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterChangeValidator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopyObject returns a generically typed copy of an object that is in memory.
// The input object is not touched.
func (in *ClusterChangeValidatorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopy returns a deep copy of a ClusterChangeValidatorList.
func (in *ClusterChangeValidatorList) DeepCopy() *ClusterChangeValidatorList {
	if in == nil {
		return nil
	}
	out := new(ClusterChangeValidatorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *ChangeValidator) DeepCopyInto(out *ChangeValidator) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopyObject returns a generically typed copy of an object that is in memory.
// The input object is not touched.
func (in *ChangeValidator) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopy returns a deep copy of a ChangeValidator.
func (in *ChangeValidator) DeepCopy() *ChangeValidator {
	if in == nil {
		return nil
	}
	out := new(ChangeValidator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *ChangeValidatorList) DeepCopyInto(out *ChangeValidatorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ChangeValidator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopyObject returns a generically typed copy of an object that is in memory.
// The input object is not touched.
func (in *ChangeValidatorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopy returns a deep copy of a ChangeValidatorList.
func (in *ChangeValidatorList) DeepCopy() *ChangeValidatorList {
	if in == nil {
		return nil
	}
	out := new(ChangeValidatorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *ChangeValidatorSpec) DeepCopyInto(out *ChangeValidatorSpec) {
	*out = *in
	in.Subject.DeepCopyInto(&out.Subject)
	if in.Operations != nil {
		in, out := &in.Operations, &out.Operations
		*out = make([]OperationType, len(*in))
		copy(*out, *in)
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]GuardRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of a ChangeValidatorSpec.
func (in *ChangeValidatorSpec) DeepCopy() *ChangeValidatorSpec {
	if in == nil {
		return nil
	}
	out := new(ChangeValidatorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *ChangeValidatorStatus) DeepCopyInto(out *ChangeValidatorStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of a ChangeValidatorStatus.
func (in *ChangeValidatorStatus) DeepCopy() *ChangeValidatorStatus {
	if in == nil {
		return nil
	}
	out := new(ChangeValidatorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *SubjectResource) DeepCopyInto(out *SubjectResource) {
	*out = *in
	if in.Names != nil {
		in, out := &in.Names, &out.Names
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy returns a deep copy of a SubjectResource.
func (in *SubjectResource) DeepCopy() *SubjectResource {
	if in == nil {
		return nil
	}
	out := new(SubjectResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *GuardRule) DeepCopyInto(out *GuardRule) {
	*out = *in
	if in.ExistingResources != nil {
		in, out := &in.ExistingResources, &out.ExistingResources
		*out = new(ExistingResourcesCheck)
		(*in).DeepCopyInto(*out)
	}
	if in.ExpressionCheck != nil {
		in, out := &in.ExpressionCheck, &out.ExpressionCheck
		*out = new(ExpressionCheck)
		**out = **in
	}
	if in.NameReferenceCheck != nil {
		in, out := &in.NameReferenceCheck, &out.NameReferenceCheck
		*out = new(NameReferenceCheck)
		(*in).DeepCopyInto(*out)
	}
	if in.ApprovalCheck != nil {
		in, out := &in.ApprovalCheck, &out.ApprovalCheck
		*out = new(ApprovalCheck)
		**out = **in
	}
	if in.AnnotationCheck != nil {
		in, out := &in.AnnotationCheck, &out.AnnotationCheck
		*out = new(AnnotationCheck)
		(*in).DeepCopyInto(*out)
	}
	if in.ManualTouchCheck != nil {
		in, out := &in.ManualTouchCheck, &out.ManualTouchCheck
		*out = new(ManualTouchCheck)
		**out = **in
	}
	if in.CheckLock != nil {
		in, out := &in.CheckLock, &out.CheckLock
		*out = new(CheckLockRule)
		(*in).DeepCopyInto(*out)
	}
	if in.DataKeySafetyCheck != nil {
		in, out := &in.DataKeySafetyCheck, &out.DataKeySafetyCheck
		*out = new(DataKeySafetyCheck)
		(*in).DeepCopyInto(*out)
	}
	if in.ServicePodSelectorCheck != nil {
		in, out := &in.ServicePodSelectorCheck, &out.ServicePodSelectorCheck
		*out = new(ServicePodSelectorCheck)
		**out = **in
	}
}

// DeepCopy returns a deep copy of a GuardRule.
func (in *GuardRule) DeepCopy() *GuardRule {
	if in == nil {
		return nil
	}
	out := new(GuardRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *ExistingResourcesCheck) DeepCopyInto(out *ExistingResourcesCheck) {
	*out = *in
	if in.LabelSelector != nil {
		in, out := &in.LabelSelector, &out.LabelSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.SameNamespace != nil {
		in, out := &in.SameNamespace, &out.SameNamespace
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy returns a deep copy of a ExistingResourcesCheck.
func (in *ExistingResourcesCheck) DeepCopy() *ExistingResourcesCheck {
	if in == nil {
		return nil
	}
	out := new(ExistingResourcesCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy returns a deep copy of an ExpressionCheck.
func (in *ExpressionCheck) DeepCopy() *ExpressionCheck {
	if in == nil {
		return nil
	}
	out := new(ExpressionCheck)
	*out = *in
	return out
}

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *NameReferenceCheck) DeepCopyInto(out *NameReferenceCheck) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]NameReferenceResource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SameNamespace != nil {
		in, out := &in.SameNamespace, &out.SameNamespace
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy returns a deep copy of a NameReferenceCheck.
func (in *NameReferenceCheck) DeepCopy() *NameReferenceCheck {
	if in == nil {
		return nil
	}
	out := new(NameReferenceCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *NameReferenceResource) DeepCopyInto(out *NameReferenceResource) {
	*out = *in
	if in.NameFields != nil {
		in, out := &in.NameFields, &out.NameFields
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy returns a deep copy of a NameReferenceResource.
func (in *NameReferenceResource) DeepCopy() *NameReferenceResource {
	if in == nil {
		return nil
	}
	out := new(NameReferenceResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *ApprovalCheck) DeepCopyInto(out *ApprovalCheck) {
	*out = *in
}

// DeepCopy returns a deep copy of an ApprovalCheck.
func (in *ApprovalCheck) DeepCopy() *ApprovalCheck {
	if in == nil {
		return nil
	}
	out := new(ApprovalCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *AnnotationCheck) DeepCopyInto(out *AnnotationCheck) {
	*out = *in
	if in.AnnotationValue != nil {
		in, out := &in.AnnotationValue, &out.AnnotationValue
		*out = new(string)
		**out = **in
	}
}

// DeepCopy returns a deep copy of an AnnotationCheck.
func (in *AnnotationCheck) DeepCopy() *AnnotationCheck {
	if in == nil {
		return nil
	}
	out := new(AnnotationCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *ManualTouchCheck) DeepCopyInto(out *ManualTouchCheck) {
	*out = *in
}

// DeepCopy returns a deep copy of a ManualTouchCheck.
func (in *ManualTouchCheck) DeepCopy() *ManualTouchCheck {
	if in == nil {
		return nil
	}
	out := new(ManualTouchCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *CheckLockRule) DeepCopyInto(out *CheckLockRule) {
	*out = *in
	if in.LockOnMutate != nil {
		in, out := &in.LockOnMutate, &out.LockOnMutate
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy returns a deep copy of a CheckLockRule.
func (in *CheckLockRule) DeepCopy() *CheckLockRule {
	if in == nil {
		return nil
	}
	out := new(CheckLockRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *ServicePodSelectorCheck) DeepCopyInto(out *ServicePodSelectorCheck) {
	*out = *in
}

// DeepCopy returns a deep copy of a ServicePodSelectorCheck.
func (in *ServicePodSelectorCheck) DeepCopy() *ServicePodSelectorCheck {
	if in == nil {
		return nil
	}
	out := new(ServicePodSelectorCheck)
	in.DeepCopyInto(out)
	return out
}

func (in *DataKeySafetyCheck) DeepCopyInto(out *DataKeySafetyCheck) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]DataKeyReferenceResource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SameNamespace != nil {
		in, out := &in.SameNamespace, &out.SameNamespace
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy returns a deep copy of a DataKeySafetyCheck.
func (in *DataKeySafetyCheck) DeepCopy() *DataKeySafetyCheck {
	if in == nil {
		return nil
	}
	out := new(DataKeySafetyCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *DataKeyReferenceResource) DeepCopyInto(out *DataKeyReferenceResource) {
	*out = *in
	if in.KeyReferenceFields != nil {
		in, out := &in.KeyReferenceFields, &out.KeyReferenceFields
		*out = make([]KeyReferenceField, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy returns a deep copy of a DataKeyReferenceResource.
func (in *DataKeyReferenceResource) DeepCopy() *DataKeyReferenceResource {
	if in == nil {
		return nil
	}
	out := new(DataKeyReferenceResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy returns a deep copy of a KeyReferenceField.
func (in *KeyReferenceField) DeepCopy() *KeyReferenceField {
	if in == nil {
		return nil
	}
	out := new(KeyReferenceField)
	*out = *in
	return out
}

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *ManualTouchMonitor) DeepCopyInto(out *ManualTouchMonitor) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopyObject returns a generically typed copy of an object that is in memory.
func (in *ManualTouchMonitor) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopy returns a deep copy of a ManualTouchMonitor.
func (in *ManualTouchMonitor) DeepCopy() *ManualTouchMonitor {
	if in == nil {
		return nil
	}
	out := new(ManualTouchMonitor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *ManualTouchMonitorList) DeepCopyInto(out *ManualTouchMonitorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ManualTouchMonitor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopyObject returns a generically typed copy of an object that is in memory.
func (in *ManualTouchMonitorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopy returns a deep copy of a ManualTouchMonitorList.
func (in *ManualTouchMonitorList) DeepCopy() *ManualTouchMonitorList {
	if in == nil {
		return nil
	}
	out := new(ManualTouchMonitorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *ManualTouchMonitorSpec) DeepCopyInto(out *ManualTouchMonitorSpec) {
	*out = *in
	if in.Subjects != nil {
		in, out := &in.Subjects, &out.Subjects
		*out = make([]MonitorSubject, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Operations != nil {
		in, out := &in.Operations, &out.Operations
		*out = make([]MonitorOperationType, len(*in))
		copy(*out, *in)
	}
	if in.UserAgentPatterns != nil {
		in, out := &in.UserAgentPatterns, &out.UserAgentPatterns
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExcludeServiceAccounts != nil {
		in, out := &in.ExcludeServiceAccounts, &out.ExcludeServiceAccounts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Alerting != nil {
		in, out := &in.Alerting, &out.Alerting
		*out = new(AlertingConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy returns a deep copy of a ManualTouchMonitorSpec.
func (in *ManualTouchMonitorSpec) DeepCopy() *ManualTouchMonitorSpec {
	if in == nil {
		return nil
	}
	out := new(ManualTouchMonitorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *ManualTouchMonitorStatus) DeepCopyInto(out *ManualTouchMonitorStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of a ManualTouchMonitorStatus.
func (in *ManualTouchMonitorStatus) DeepCopy() *ManualTouchMonitorStatus {
	if in == nil {
		return nil
	}
	out := new(ManualTouchMonitorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *MonitorSubject) DeepCopyInto(out *MonitorSubject) {
	*out = *in
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy returns a deep copy of a MonitorSubject.
func (in *MonitorSubject) DeepCopy() *MonitorSubject {
	if in == nil {
		return nil
	}
	out := new(MonitorSubject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *AlertingConfig) DeepCopyInto(out *AlertingConfig) {
	*out = *in
	if in.PrometheusLabels != nil {
		in, out := &in.PrometheusLabels, &out.PrometheusLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy returns a deep copy of an AlertingConfig.
func (in *AlertingConfig) DeepCopy() *AlertingConfig {
	if in == nil {
		return nil
	}
	out := new(AlertingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *ManualTouchEvent) DeepCopyInto(out *ManualTouchEvent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopyObject returns a generically typed copy of an object that is in memory.
func (in *ManualTouchEvent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopy returns a deep copy of a ManualTouchEvent.
func (in *ManualTouchEvent) DeepCopy() *ManualTouchEvent {
	if in == nil {
		return nil
	}
	out := new(ManualTouchEvent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *ManualTouchEventList) DeepCopyInto(out *ManualTouchEventList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ManualTouchEvent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopyObject returns a generically typed copy of an object that is in memory.
func (in *ManualTouchEventList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopy returns a deep copy of a ManualTouchEventList.
func (in *ManualTouchEventList) DeepCopy() *ManualTouchEventList {
	if in == nil {
		return nil
	}
	out := new(ManualTouchEventList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *ManualTouchEventSpec) DeepCopyInto(out *ManualTouchEventSpec) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
}

// DeepCopy returns a deep copy of a ManualTouchEventSpec.
func (in *ManualTouchEventSpec) DeepCopy() *ManualTouchEventSpec {
	if in == nil {
		return nil
	}
	out := new(ManualTouchEventSpec)
	in.DeepCopyInto(out)
	return out
}

